//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.CalculationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://docs.microsoft.com/en-us/previous-versions/dotnet/articles/ms951273(v=msd" +
        "n.10)?redirectedfrom=MSDN", ConfigurationName="CalculationService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://docs.microsoft.com/en-us/previous-versions/dotnet/articles/ms951273(v=msd" +
            "n.10)?redirectedfrom=MSDN/IService/Sum", ReplyAction="https://docs.microsoft.com/en-us/previous-versions/dotnet/articles/ms951273(v=msd" +
            "n.10)?redirectedfrom=MSDN/IService/SumResponse")]
        int Sum(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://docs.microsoft.com/en-us/previous-versions/dotnet/articles/ms951273(v=msd" +
            "n.10)?redirectedfrom=MSDN/IService/Sum", ReplyAction="https://docs.microsoft.com/en-us/previous-versions/dotnet/articles/ms951273(v=msd" +
            "n.10)?redirectedfrom=MSDN/IService/SumResponse")]
        System.Threading.Tasks.Task<int> SumAsync(int a, int b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Client.CalculationService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Client.CalculationService.IService>, Client.CalculationService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Sum(int a, int b) {
            return base.Channel.Sum(a, b);
        }
        
        public System.Threading.Tasks.Task<int> SumAsync(int a, int b) {
            return base.Channel.SumAsync(a, b);
        }
    }
}
